# Generated by Django 3.1.7 on 2021-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('albums', models.CharField(max_length=200)),
                ('tracks', models.CharField(max_length=200)),
                ('self_url', models.CharField(max_length=31)),
            ],
        ),
    ]
