# Generated by Django 3.1.7 on 2021-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('tracks', models.CharField(max_length=200)),
                ('self_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField()),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('self_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='self_url',
            field=models.CharField(max_length=200),
        ),
    ]
