# Generated by Django 3.1.7 on 2021-05-02 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210502_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.album'),
        ),
    ]
