# Generated by Django 3.1.7 on 2021-05-02 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_track_album_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.artist'),
        ),
    ]
